flowchart TB
    supervisor["fa:fa-gear Supervisor"]
    server["fa:fa-server OpAMP server"]
    collector["fa:fa-terminal Collector"]

    supervisor <-->|OpAMP| server
    supervisor -->|exec/kill| collector
    collector -->|Status| supervisor


class supervisor,collector,server box;
%% class PR,main,Release,uu,Hotfix,Testing,release2,artifacts rounded;
%% class upstream,distro container;
