flowchart TB
    server["fa:fa-server OpAMP server"]
    collector["fa:fa-terminal Collector"]
    supervisor["fa:fa-gear Supervisor"]

    server <-->|OpAMP| supervisor
    collector -->|"Status (OpAMP)"| supervisor
    supervisor -->|exec/kill| collector


class supervisor,collector,server box;
%% class PR,main,Release,uu,Hotfix,Testing,release2,artifacts rounded;
%% class upstream,distro container;
