flowchart LR
    server["fa:fa-server OpAMP server"]
    collector["fa:fa-terminal Collector"]

    server -->|"Config (OpAMP)"| collector
    collector -->|"Status (OpAMP)"| server

class collector,server box;