flowchart TB
    collector["fa:fa-terminal Collector"]
    server["fa:fa-server OpAMP server"]

    server -->|"Config (OpAMP)"| collector
    collector -->|"Status (OpAMP)"| server

class collector,server box;